services:
  - type: web
    name: free-aistudio-yt-kimi
    runtime: node
    buildCommand: yarn install
    startCommand: node server.js
    envVars:
      - key: OPENROUTER_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
    nativePackages:
      - ffmpeg
      - python3
      - python3-pip
